@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
'allowmixing
'left to right direction
skinparam DefaultFontName "Open Sans"
skinparam linetype polyline
skinparam rectangle {
    roundCorner<<Concept>> 25
}

LAYOUT_WITH_LEGEND()

title
| Title: | Generalized Databricks C4 System Diagram |
| As of  | %date("YYYY-MM-dd") |
| PlantUML Version | %version() |
end title


!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(admin, "Administrator")
Enterprise_Boundary(Generalized, "Enterprise Boundary") {
System_Boundary(c1, "Sample System") {
    Container(web_app, \
    "Web Application", \
    "C#, ASP.NET Core 2.1 MVC", \
    "Allows users to compare multiple Twitter timelines")
}
System(twitter, "Twitter")
}


Rel(admin, web_app, "Uses", "HTTPS")
Rel(web_app, twitter, "Gets tweets from", "HTTPS")



LAYOUT_LANDSCAPE()
@enduml