@startjson
{
  "groups": {
    "admin": {
      "group_description": "Workspace Administrators",
      "permissions": {
        "clusters": "CAN_MANAGE",
        "cluster_policies": "CAN_MANAGE",
        "delta_live_tables_pipelines": "CAN_MANAGE",
        "jobs": "CAN_MANAGE",
        "mlflow_experiments": "CAN_MANAGE",
        "mlflow_registered_models": "CAN_MANAGE",
        "passwords": "CAN_MANAGE",
        "instance_pools": "CAN_MANAGE",
        "repos": "CAN_MANAGE",
        "serve_endpoints": "CAN_MANAGE",
        "sql_warehouses": "CAN_MANAGE",
        "tokens": "CAN_MANAGE",
        "secret_scopes": "CAN_MANAGE",
        "workspaces": "CAN_MANAGE",
        "users": "CAN_MANAGE",
        "groups": "CAN_MANAGE",
        "roles": "CAN_MANAGE"
      },
      "entitlements": {
        "allow_cluster_create": true,
        "allow_instance_pool_create": true,
        "allow_job_create": true,
        "allow_mlflow_experiment_create": true,
        "allow_mlflow_registered_model_create": true,
        "allow_repo_create": true,
        "allow_serve_endpoint_create": true,
        "allow_sql_warehouse_create": true,
        "allow_token_create": true,
        "allow_workspace_create": true,
        "allow_user_create": true,
        "allow_group_create": true,
        "allow_role_create": true
      }
    },
      "mle_ds_lead": {
      "group_description": "MLE Data Scientist Leads",
      "permissions": {
        "clusters": "CAN_MANAGE",
        "cluster_policies": "CAN_MANAGE",
        "delta_live_tables_pipelines": "CAN_MANAGE",
        "jobs": "CAN_MANAGE",
        "mlflow_experiments": "CAN_MANAGE",
        "mlflow_registered_models": "CAN_MANAGE",
        "passwords": "CAN_MANAGE",
        "instance_pools": "CAN_MANAGE",
        "repos": "CAN_MANAGE",
        "serve_endpoints": "CAN_MANAGE",
        "sql_warehouses": "CAN_MANAGE",
        "tokens": "CAN_MANAGE",
        "secret_scopes": "CAN_MANAGE",
        "workspaces": "CAN_MANAGE",
        "users": "CAN_MANAGE",
        "groups": "CAN_MANAGE",
        "roles": "CAN_MANAGE"
      },
      "entitlements": {
        "allow_cluster_create": true,
        "allow_instance_pool_create": true,
        "allow_job_create": true,
        "allow_mlflow_experiment_create": true,
        "allow_mlflow_registered_model_create": true,
        "allow_repo_create": true,
        "allow_serve_endpoint_create": true,
        "allow_sql_warehouse_create": true,
        "allow_token_create": true,
        "allow_workspace_create": true,
        "allow_user_create": true,
        "allow_group_create": true,
        "allow_role_create": true
      }
    },
      "deployer": {
      "group_description": "Deployers",
      "permissions": {
        "clusters": "CAN_MANAGE",
        "cluster_policies": "CAN_MANAGE",
        "delta_live_tables_pipelines": "CAN_MANAGE",
        "jobs": "CAN_MANAGE",
        "mlflow_experiments": "CAN_MANAGE",
        "mlflow_registered_models": "CAN_MANAGE",
        "passwords": "CAN_MANAGE",
        "instance_pools": "CAN_MANAGE",
        "repos": "CAN_MANAGE",
        "serve_endpoints": "CAN_MANAGE",
        "sql_warehouses": "CAN_MANAGE",
        "tokens": "CAN_MANAGE",
        "secret_scopes": "CAN_MANAGE",
        "workspaces": "CAN_MANAGE",
        "users": "CAN_MANAGE",
        "groups": "CAN_MANAGE",
        "roles": "CAN_MANAGE"
      },
      "entitlements": {
        "allow_cluster_create": true,
        "allow_instance_pool_create": true,
        "allow_job_create": true,
        "allow_mlflow_experiment_create": true,
        "allow_mlflow_registered_model_create": true,
        "allow_repo_create": true,
        "allow_serve_endpoint_create": true,
        "allow_sql_warehouse_create": true,
        "allow_token_create": true,
        "allow_workspace_create": true,
        "allow_user_create": true,
        "allow_group_create": true,
        "allow_role_create": true
      }
    },
      "mle_ds": {
      "group_description": "Machine Learning Engineer Data Scientist",
      "permissions": {
        "clusters": "CAN_MANAGE",
        "cluster_policies": "CAN_MANAGE",
        "delta_live_tables_pipelines": "CAN_MANAGE",
        "jobs": "CAN_MANAGE",
        "mlflow_experiments": "CAN_MANAGE",
        "mlflow_registered_models": "CAN_MANAGE",
        "passwords": "CAN_MANAGE",
        "instance_pools": "CAN_MANAGE",
        "repos": "CAN_MANAGE",
        "serve_endpoints": "CAN_MANAGE",
        "sql_warehouses": "CAN_MANAGE",
        "tokens": "CAN_MANAGE",
        "secret_scopes": "CAN_MANAGE",
        "workspaces": "CAN_MANAGE",
        "users": "CAN_MANAGE",
        "groups": "CAN_MANAGE",
        "roles": "CAN_MANAGE"
      },
      "entitlements": {
        "allow_cluster_create": true,
        "allow_instance_pool_create": true,
        "allow_job_create": true,
        "allow_mlflow_experiment_create": true,
        "allow_mlflow_registered_model_create": true,
        "allow_repo_create": true,
        "allow_serve_endpoint_create": true,
        "allow_sql_warehouse_create": true,
        "allow_token_create": true,
        "allow_workspace_create": true,
        "allow_user_create": true,
        "allow_group_create": true,
        "allow_role_create": true
      }
    },
      "bi_analyst": {
      "group_description": "Business Intelligence Analyst",
      "permissions": {
        "clusters": "CAN_MANAGE",
        "cluster_policies": "CAN_MANAGE",
        "delta_live_tables_pipelines": "CAN_MANAGE",
        "jobs": "CAN_MANAGE",
        "mlflow_experiments": "CAN_MANAGE",
        "mlflow_registered_models": "CAN_MANAGE",
        "passwords": "CAN_MANAGE",
        "instance_pools": "CAN_MANAGE",
        "repos": "CAN_MANAGE",
        "serve_endpoints": "CAN_MANAGE",
        "sql_warehouses": "CAN_MANAGE",
        "tokens": "CAN_MANAGE",
        "secret_scopes": "CAN_MANAGE",
        "workspaces": "CAN_MANAGE",
        "users": "CAN_MANAGE",
        "groups": "CAN_MANAGE",
        "roles": "CAN_MANAGE"
      },
      "entitlements": {
        "allow_cluster_create": true,
        "allow_instance_pool_create": true,
        "allow_job_create": true,
        "allow_mlflow_experiment_create": true,
        "allow_mlflow_registered_model_create": true,
        "allow_repo_create": true,
        "allow_serve_endpoint_create": true,
        "allow_sql_warehouse_create": true,
        "allow_token_create": true,
        "allow_workspace_create": true,
        "allow_user_create": true,
        "allow_group_create": true,
        "allow_role_create": true
      }
    },
      "data_engineer": {
      "group_description": "Data Engineer",
      "permissions": {
        "clusters": "CAN_MANAGE",
        "cluster_policies": "CAN_MANAGE",
        "delta_live_tables_pipelines": "CAN_MANAGE",
        "jobs": "CAN_MANAGE",
        "mlflow_experiments": "CAN_MANAGE",
        "mlflow_registered_models": "CAN_MANAGE",
        "passwords": "CAN_MANAGE",
        "instance_pools": "CAN_MANAGE",
        "repos": "CAN_MANAGE",
        "serve_endpoints": "CAN_MANAGE",
        "sql_warehouses": "CAN_MANAGE",
        "tokens": "CAN_MANAGE",
        "secret_scopes": "CAN_MANAGE",
        "workspaces": "CAN_MANAGE",
        "users": "CAN_MANAGE",
        "groups": "CAN_MANAGE",
        "roles": "CAN_MANAGE"
      },
      "entitlements": {
        "allow_cluster_create": true,
        "allow_instance_pool_create": true,
        "allow_job_create": true,
        "allow_mlflow_experiment_create": true,
        "allow_mlflow_registered_model_create": true,
        "allow_repo_create": true,
        "allow_serve_endpoint_create": true,
        "allow_sql_warehouse_create": true,
        "allow_token_create": true,
        "allow_workspace_create": true,
        "allow_user_create": true,
        "allow_group_create": true,
        "allow_role_create": true
      }
    }
  }
}
@endjson
